### ISSUE TITLE
função "eqv?"

### ISSUE THREAD

**Issue by miguelarauj1o** [miguelarauj1o/skimscheme#10]
Uma função eqv? para verificar equivalência entre valores. Veja Seção [6.1](http://www.schemers.org/Documents/Standards/R5RS/r5rs.pdf) da especificação de Scheme para ter uma noção sobre como ela funcionará. Tenha em mente, porém, que não é necessário fazer comparação por referência. **Comparação por valor é suficiente**.

**Comment by miguelarauj1o** [comment]
problems here, problems there, problems everywhere!

**Comment by paulolieuthier** [comment]
hahaha

**Comment by miguelarauj1o** [comment]
Esta função (**com 99% de certeza**) está falhando.
Pelo o que eu vi em DottedList no LispVal, ele é uma lista de LispVal + LispVal. O que eu fiz verifica uma lista de LispVal, restando um LispVal ao final.

**Comment by miguelarauj1o** [comment]
@paulolieuthier, @rnns... algum de vcs podem me fornecer um exemplo de dottedlist?

**Comment by miguelarauj1o** [comment]
Tô cansado de ser iludido por essa safada dessa função.
**Pra mim ela está correta**

**Comment by miguelarauj1o** [comment]
Abre, fecha, abre, fecha, abre, fecha.... pense num cabaré isso. 
Se este exemplo for válido: **"(eqv? ((1 2) 2) ((1 2) 2))"**, O projeto está retornando #f, mas deveria retornar #t... :-1:

**Comment by miguelarauj1o** [comment]
https://www.youtube.com/watch?v=09m0B8RRiEE

**Comment by paulolieuthier** [comment]
Quero ver o `set!` agora.

**Comment by miguelarauj1o** [comment]
@paulolieuthier, #4. :D

**Comment by paulolieuthier** [comment]
É quente.
