### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by miguelarauj1o** [miguelarauj1o/skimscheme#12]
Além do interpretador, a equipe deve construir pelo menos **dez** programas corretos e que testem todas as funcionalidades implementadas pelo interpretador. Esses testes devem incluir situações onde várias funcionalidades são combinadas. Os programas desenvolvidos devem estar disponíveis no momento da apresentação do projeto. **Pelo menos um desses programas deve implementar o algoritmo Quicksort recursivamente e pelo menos dois devem usar clausuras léxicas**.

**Comment by miguelarauj1o** [comment]
@rodrigoalvesvieira, se possível, faz uns 20 testes.

**Comment by miguelarauj1o** [comment]
@KaoozFreitas, boa! Amanhã eu tentarei fazer o quicksort e, se possível, closures.

**Comment by miguelarauj1o** [comment]
@rodrigoalvesvieira, falta 4 casos de testes para fechar o mínino necessário. Tu pode criar eles usando closures?

**Comment by miguelarauj1o** [comment]
@rodrigoalvesvieira, @KaoozFreitas... eu estou desenrolando o quicksort. Vocês conseguiram fazer mais algum teste?

**Comment by miguelarauj1o** [comment]
@rodrigoalvesvieira, @KaoozFreitas: append function tested.

**Comment by rafaelfccg** [comment]
tests.txt  -6  result equal to 0 in my implementation
tests.txt  -7  result equal to 1 in my implementation
tests.txt  -8  result equal to #f in my implementation
tests.txt  -9  result equal to a make-clousure

**Comment by miguelarauj1o** [comment]
Estranhamente, quicksort funciona quando invertemos a seguinte linha do SSInterpreter.hs:
`id (Map.lookup var (union s env)`
por:
`id (Map.lookup var (union env s)`

Tem algo relacionado com as prioridades, mas...

**Comment by rodrigoalvesvieira** [comment]
Pronto @miguelarauj1o!
