### ISSUE TITLE
Chamadas recursivas de funções

### ISSUE THREAD

**Issue by miguelarauj1o** [miguelarauj1o/skimscheme#2]
(Seção [4.1.3](http://www.schemers.org/Documents/Standards/R5RS/r5rs.pdf) da especificação de Scheme).

**Comment by miguelarauj1o** [comment]
@rodrigoalvesvieira, @KaoozFreitas... aparentemente chamada recursiva de funções já está implementado no projeto.
Segue um exemplo de fatorial (retorna #f --o que é esperado--):
`"(begin (define fat (lambda (n) (if (eqv? n 0) 1 (* n (fat (- n 1)))))) (lt? (fat 5) 100))"`

**Comment by paulolieuthier** [comment]
Gogogo quicksort.

**Comment by miguelarauj1o** [comment]
calma jovem, calma.

**Comment by miguelarauj1o** [comment]
Goodbye #2. Hello #11!

**Comment by miguelarauj1o** [comment]
@fernandocastor:

"Recursão já funciona no interpretador, mas apenas com variáveis globais. A parte de passagem de parâmetros do interpretador que vocês receberam está furada (as variáveis criadas não são locais de fato e deveriam ser). Logo, você não precisa de precauções especiais para fazer recursão funcionar. Basta implementar variáveis locais e ajustar a forma como os argumentos são associados às variáveis (para que essas variáveis se comportem como variáveis locais de fato)."
